/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehiculosRouteImport } from './routes/vehiculos'
import { Route as TiemposRespuestaRouteImport } from './routes/tiempos-respuesta'
import { Route as ServiciosFijosRouteImport } from './routes/servicios-fijos'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as PasajerosPcdRouteImport } from './routes/pasajeros-pcd'
import { Route as PasajeroRouteImport } from './routes/pasajero'
import { Route as OperacionRouteImport } from './routes/operacion'
import { Route as MonitoreoRouteImport } from './routes/monitoreo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FormatosRouteImport } from './routes/formatos'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FacturacionRouteImport } from './routes/facturacion'
import { Route as CumplimientoRouteImport } from './routes/cumplimiento'
import { Route as CuentasRouteImport } from './routes/cuentas'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ConductoresRouteImport } from './routes/conductores'
import { Route as AyudaRouteImport } from './routes/ayuda'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CrmIndexRouteImport } from './routes/crm.index'
import { Route as ConductorIndexRouteImport } from './routes/conductor.index'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as LegalTerminosRouteImport } from './routes/legal.terminos'
import { Route as LegalPrivacidadRouteImport } from './routes/legal.privacidad'
import { Route as CrmVentasRouteImport } from './routes/crm.ventas'
import { Route as CrmPipelineRouteImport } from './routes/crm.pipeline'
import { Route as CrmLoginRouteImport } from './routes/crm.login'
import { Route as CrmEquipoRouteImport } from './routes/crm.equipo'
import { Route as CrmCumpleanosRouteImport } from './routes/crm.cumpleanos'
import { Route as CrmCreditosRouteImport } from './routes/crm.creditos'
import { Route as CrmConcesionariosRouteImport } from './routes/crm.concesionarios'
import { Route as CrmClientesRouteImport } from './routes/crm.clientes'
import { Route as CrmCatalogoRouteImport } from './routes/crm.catalogo'
import { Route as CrmCapacidadesRouteImport } from './routes/crm.capacidades'
import { Route as CrmAsesoresRouteImport } from './routes/crm.asesores'
import { Route as ConductorLoginRouteImport } from './routes/conductor.login'
import { Route as ConductorServicioIdRouteImport } from './routes/conductor.servicio.$id'
import { Route as ApiPublicConductorLoginRouteImport } from './routes/api/public/conductor-login'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPushProcessRouteImport } from './routes/api/public/push.process'

const VehiculosRoute = VehiculosRouteImport.update({
  id: '/vehiculos',
  path: '/vehiculos',
  getParentRoute: () => rootRouteImport,
} as any)
const TiemposRespuestaRoute = TiemposRespuestaRouteImport.update({
  id: '/tiempos-respuesta',
  path: '/tiempos-respuesta',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosFijosRoute = ServiciosFijosRouteImport.update({
  id: '/servicios-fijos',
  path: '/servicios-fijos',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const PasajerosPcdRoute = PasajerosPcdRouteImport.update({
  id: '/pasajeros-pcd',
  path: '/pasajeros-pcd',
  getParentRoute: () => rootRouteImport,
} as any)
const PasajeroRoute = PasajeroRouteImport.update({
  id: '/pasajero',
  path: '/pasajero',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacionRoute = OperacionRouteImport.update({
  id: '/operacion',
  path: '/operacion',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoreoRoute = MonitoreoRouteImport.update({
  id: '/monitoreo',
  path: '/monitoreo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FormatosRoute = FormatosRouteImport.update({
  id: '/formatos',
  path: '/formatos',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturacionRoute = FacturacionRouteImport.update({
  id: '/facturacion',
  path: '/facturacion',
  getParentRoute: () => rootRouteImport,
} as any)
const CumplimientoRoute = CumplimientoRouteImport.update({
  id: '/cumplimiento',
  path: '/cumplimiento',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentasRoute = CuentasRouteImport.update({
  id: '/cuentas',
  path: '/cuentas',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ConductoresRoute = ConductoresRouteImport.update({
  id: '/conductores',
  path: '/conductores',
  getParentRoute: () => rootRouteImport,
} as any)
const AyudaRoute = AyudaRouteImport.update({
  id: '/ayuda',
  path: '/ayuda',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmIndexRoute = CrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrmRoute,
} as any)
const ConductorIndexRoute = ConductorIndexRouteImport.update({
  id: '/conductor/',
  path: '/conductor/',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTerminosRoute = LegalTerminosRouteImport.update({
  id: '/legal/terminos',
  path: '/legal/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacidadRoute = LegalPrivacidadRouteImport.update({
  id: '/legal/privacidad',
  path: '/legal/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmVentasRoute = CrmVentasRouteImport.update({
  id: '/ventas',
  path: '/ventas',
  getParentRoute: () => CrmRoute,
} as any)
const CrmPipelineRoute = CrmPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => CrmRoute,
} as any)
const CrmLoginRoute = CrmLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => CrmRoute,
} as any)
const CrmEquipoRoute = CrmEquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => CrmRoute,
} as any)
const CrmCumpleanosRoute = CrmCumpleanosRouteImport.update({
  id: '/cumpleanos',
  path: '/cumpleanos',
  getParentRoute: () => CrmRoute,
} as any)
const CrmCreditosRoute = CrmCreditosRouteImport.update({
  id: '/creditos',
  path: '/creditos',
  getParentRoute: () => CrmRoute,
} as any)
const CrmConcesionariosRoute = CrmConcesionariosRouteImport.update({
  id: '/concesionarios',
  path: '/concesionarios',
  getParentRoute: () => CrmRoute,
} as any)
const CrmClientesRoute = CrmClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => CrmRoute,
} as any)
const CrmCatalogoRoute = CrmCatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => CrmRoute,
} as any)
const CrmCapacidadesRoute = CrmCapacidadesRouteImport.update({
  id: '/capacidades',
  path: '/capacidades',
  getParentRoute: () => CrmRoute,
} as any)
const CrmAsesoresRoute = CrmAsesoresRouteImport.update({
  id: '/asesores',
  path: '/asesores',
  getParentRoute: () => CrmRoute,
} as any)
const ConductorLoginRoute = ConductorLoginRouteImport.update({
  id: '/conductor/login',
  path: '/conductor/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ConductorServicioIdRoute = ConductorServicioIdRouteImport.update({
  id: '/conductor/servicio/$id',
  path: '/conductor/servicio/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicConductorLoginRoute = ApiPublicConductorLoginRouteImport.update({
  id: '/api/public/conductor-login',
  path: '/api/public/conductor-login',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushProcessRoute = ApiPublicPushProcessRouteImport.update({
  id: '/api/public/push/process',
  path: '/api/public/push/process',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/ayuda': typeof AyudaRoute
  '/conductores': typeof ConductoresRoute
  '/crm': typeof CrmRouteWithChildren
  '/cuentas': typeof CuentasRoute
  '/cumplimiento': typeof CumplimientoRoute
  '/facturacion': typeof FacturacionRoute
  '/feedback': typeof FeedbackRoute
  '/formatos': typeof FormatosRoute
  '/login': typeof LoginRoute
  '/monitoreo': typeof MonitoreoRoute
  '/operacion': typeof OperacionRoute
  '/pasajero': typeof PasajeroRoute
  '/pasajeros-pcd': typeof PasajerosPcdRoute
  '/reportes': typeof ReportesRoute
  '/servicios': typeof ServiciosRoute
  '/servicios-fijos': typeof ServiciosFijosRoute
  '/tiempos-respuesta': typeof TiemposRespuestaRoute
  '/vehiculos': typeof VehiculosRoute
  '/conductor/login': typeof ConductorLoginRoute
  '/crm/asesores': typeof CrmAsesoresRoute
  '/crm/capacidades': typeof CrmCapacidadesRoute
  '/crm/catalogo': typeof CrmCatalogoRoute
  '/crm/clientes': typeof CrmClientesRoute
  '/crm/concesionarios': typeof CrmConcesionariosRoute
  '/crm/creditos': typeof CrmCreditosRoute
  '/crm/cumpleanos': typeof CrmCumpleanosRoute
  '/crm/equipo': typeof CrmEquipoRoute
  '/crm/login': typeof CrmLoginRoute
  '/crm/pipeline': typeof CrmPipelineRoute
  '/crm/ventas': typeof CrmVentasRoute
  '/legal/privacidad': typeof LegalPrivacidadRoute
  '/legal/terminos': typeof LegalTerminosRoute
  '/r/$token': typeof RTokenRoute
  '/conductor/': typeof ConductorIndexRoute
  '/crm/': typeof CrmIndexRoute
  '/api/public/conductor-login': typeof ApiPublicConductorLoginRoute
  '/conductor/servicio/$id': typeof ConductorServicioIdRoute
  '/api/public/push/process': typeof ApiPublicPushProcessRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/ayuda': typeof AyudaRoute
  '/conductores': typeof ConductoresRoute
  '/cuentas': typeof CuentasRoute
  '/cumplimiento': typeof CumplimientoRoute
  '/facturacion': typeof FacturacionRoute
  '/feedback': typeof FeedbackRoute
  '/formatos': typeof FormatosRoute
  '/login': typeof LoginRoute
  '/monitoreo': typeof MonitoreoRoute
  '/operacion': typeof OperacionRoute
  '/pasajero': typeof PasajeroRoute
  '/pasajeros-pcd': typeof PasajerosPcdRoute
  '/reportes': typeof ReportesRoute
  '/servicios': typeof ServiciosRoute
  '/servicios-fijos': typeof ServiciosFijosRoute
  '/tiempos-respuesta': typeof TiemposRespuestaRoute
  '/vehiculos': typeof VehiculosRoute
  '/conductor/login': typeof ConductorLoginRoute
  '/crm/asesores': typeof CrmAsesoresRoute
  '/crm/capacidades': typeof CrmCapacidadesRoute
  '/crm/catalogo': typeof CrmCatalogoRoute
  '/crm/clientes': typeof CrmClientesRoute
  '/crm/concesionarios': typeof CrmConcesionariosRoute
  '/crm/creditos': typeof CrmCreditosRoute
  '/crm/cumpleanos': typeof CrmCumpleanosRoute
  '/crm/equipo': typeof CrmEquipoRoute
  '/crm/login': typeof CrmLoginRoute
  '/crm/pipeline': typeof CrmPipelineRoute
  '/crm/ventas': typeof CrmVentasRoute
  '/legal/privacidad': typeof LegalPrivacidadRoute
  '/legal/terminos': typeof LegalTerminosRoute
  '/r/$token': typeof RTokenRoute
  '/conductor': typeof ConductorIndexRoute
  '/crm': typeof CrmIndexRoute
  '/api/public/conductor-login': typeof ApiPublicConductorLoginRoute
  '/conductor/servicio/$id': typeof ConductorServicioIdRoute
  '/api/public/push/process': typeof ApiPublicPushProcessRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/ayuda': typeof AyudaRoute
  '/conductores': typeof ConductoresRoute
  '/crm': typeof CrmRouteWithChildren
  '/cuentas': typeof CuentasRoute
  '/cumplimiento': typeof CumplimientoRoute
  '/facturacion': typeof FacturacionRoute
  '/feedback': typeof FeedbackRoute
  '/formatos': typeof FormatosRoute
  '/login': typeof LoginRoute
  '/monitoreo': typeof MonitoreoRoute
  '/operacion': typeof OperacionRoute
  '/pasajero': typeof PasajeroRoute
  '/pasajeros-pcd': typeof PasajerosPcdRoute
  '/reportes': typeof ReportesRoute
  '/servicios': typeof ServiciosRoute
  '/servicios-fijos': typeof ServiciosFijosRoute
  '/tiempos-respuesta': typeof TiemposRespuestaRoute
  '/vehiculos': typeof VehiculosRoute
  '/conductor/login': typeof ConductorLoginRoute
  '/crm/asesores': typeof CrmAsesoresRoute
  '/crm/capacidades': typeof CrmCapacidadesRoute
  '/crm/catalogo': typeof CrmCatalogoRoute
  '/crm/clientes': typeof CrmClientesRoute
  '/crm/concesionarios': typeof CrmConcesionariosRoute
  '/crm/creditos': typeof CrmCreditosRoute
  '/crm/cumpleanos': typeof CrmCumpleanosRoute
  '/crm/equipo': typeof CrmEquipoRoute
  '/crm/login': typeof CrmLoginRoute
  '/crm/pipeline': typeof CrmPipelineRoute
  '/crm/ventas': typeof CrmVentasRoute
  '/legal/privacidad': typeof LegalPrivacidadRoute
  '/legal/terminos': typeof LegalTerminosRoute
  '/r/$token': typeof RTokenRoute
  '/conductor/': typeof ConductorIndexRoute
  '/crm/': typeof CrmIndexRoute
  '/api/public/conductor-login': typeof ApiPublicConductorLoginRoute
  '/conductor/servicio/$id': typeof ConductorServicioIdRoute
  '/api/public/push/process': typeof ApiPublicPushProcessRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/ayuda'
    | '/conductores'
    | '/crm'
    | '/cuentas'
    | '/cumplimiento'
    | '/facturacion'
    | '/feedback'
    | '/formatos'
    | '/login'
    | '/monitoreo'
    | '/operacion'
    | '/pasajero'
    | '/pasajeros-pcd'
    | '/reportes'
    | '/servicios'
    | '/servicios-fijos'
    | '/tiempos-respuesta'
    | '/vehiculos'
    | '/conductor/login'
    | '/crm/asesores'
    | '/crm/capacidades'
    | '/crm/catalogo'
    | '/crm/clientes'
    | '/crm/concesionarios'
    | '/crm/creditos'
    | '/crm/cumpleanos'
    | '/crm/equipo'
    | '/crm/login'
    | '/crm/pipeline'
    | '/crm/ventas'
    | '/legal/privacidad'
    | '/legal/terminos'
    | '/r/$token'
    | '/conductor/'
    | '/crm/'
    | '/api/public/conductor-login'
    | '/conductor/servicio/$id'
    | '/api/public/push/process'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/ayuda'
    | '/conductores'
    | '/cuentas'
    | '/cumplimiento'
    | '/facturacion'
    | '/feedback'
    | '/formatos'
    | '/login'
    | '/monitoreo'
    | '/operacion'
    | '/pasajero'
    | '/pasajeros-pcd'
    | '/reportes'
    | '/servicios'
    | '/servicios-fijos'
    | '/tiempos-respuesta'
    | '/vehiculos'
    | '/conductor/login'
    | '/crm/asesores'
    | '/crm/capacidades'
    | '/crm/catalogo'
    | '/crm/clientes'
    | '/crm/concesionarios'
    | '/crm/creditos'
    | '/crm/cumpleanos'
    | '/crm/equipo'
    | '/crm/login'
    | '/crm/pipeline'
    | '/crm/ventas'
    | '/legal/privacidad'
    | '/legal/terminos'
    | '/r/$token'
    | '/conductor'
    | '/crm'
    | '/api/public/conductor-login'
    | '/conductor/servicio/$id'
    | '/api/public/push/process'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/ayuda'
    | '/conductores'
    | '/crm'
    | '/cuentas'
    | '/cumplimiento'
    | '/facturacion'
    | '/feedback'
    | '/formatos'
    | '/login'
    | '/monitoreo'
    | '/operacion'
    | '/pasajero'
    | '/pasajeros-pcd'
    | '/reportes'
    | '/servicios'
    | '/servicios-fijos'
    | '/tiempos-respuesta'
    | '/vehiculos'
    | '/conductor/login'
    | '/crm/asesores'
    | '/crm/capacidades'
    | '/crm/catalogo'
    | '/crm/clientes'
    | '/crm/concesionarios'
    | '/crm/creditos'
    | '/crm/cumpleanos'
    | '/crm/equipo'
    | '/crm/login'
    | '/crm/pipeline'
    | '/crm/ventas'
    | '/legal/privacidad'
    | '/legal/terminos'
    | '/r/$token'
    | '/conductor/'
    | '/crm/'
    | '/api/public/conductor-login'
    | '/conductor/servicio/$id'
    | '/api/public/push/process'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  AyudaRoute: typeof AyudaRoute
  ConductoresRoute: typeof ConductoresRoute
  CrmRoute: typeof CrmRouteWithChildren
  CuentasRoute: typeof CuentasRoute
  CumplimientoRoute: typeof CumplimientoRoute
  FacturacionRoute: typeof FacturacionRoute
  FeedbackRoute: typeof FeedbackRoute
  FormatosRoute: typeof FormatosRoute
  LoginRoute: typeof LoginRoute
  MonitoreoRoute: typeof MonitoreoRoute
  OperacionRoute: typeof OperacionRoute
  PasajeroRoute: typeof PasajeroRoute
  PasajerosPcdRoute: typeof PasajerosPcdRoute
  ReportesRoute: typeof ReportesRoute
  ServiciosRoute: typeof ServiciosRoute
  ServiciosFijosRoute: typeof ServiciosFijosRoute
  TiemposRespuestaRoute: typeof TiemposRespuestaRoute
  VehiculosRoute: typeof VehiculosRoute
  ConductorLoginRoute: typeof ConductorLoginRoute
  LegalPrivacidadRoute: typeof LegalPrivacidadRoute
  LegalTerminosRoute: typeof LegalTerminosRoute
  RTokenRoute: typeof RTokenRoute
  ConductorIndexRoute: typeof ConductorIndexRoute
  ApiPublicConductorLoginRoute: typeof ApiPublicConductorLoginRoute
  ConductorServicioIdRoute: typeof ConductorServicioIdRoute
  ApiPublicPushProcessRoute: typeof ApiPublicPushProcessRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehiculos': {
      id: '/vehiculos'
      path: '/vehiculos'
      fullPath: '/vehiculos'
      preLoaderRoute: typeof VehiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tiempos-respuesta': {
      id: '/tiempos-respuesta'
      path: '/tiempos-respuesta'
      fullPath: '/tiempos-respuesta'
      preLoaderRoute: typeof TiemposRespuestaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios-fijos': {
      id: '/servicios-fijos'
      path: '/servicios-fijos'
      fullPath: '/servicios-fijos'
      preLoaderRoute: typeof ServiciosFijosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pasajeros-pcd': {
      id: '/pasajeros-pcd'
      path: '/pasajeros-pcd'
      fullPath: '/pasajeros-pcd'
      preLoaderRoute: typeof PasajerosPcdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pasajero': {
      id: '/pasajero'
      path: '/pasajero'
      fullPath: '/pasajero'
      preLoaderRoute: typeof PasajeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacion': {
      id: '/operacion'
      path: '/operacion'
      fullPath: '/operacion'
      preLoaderRoute: typeof OperacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoreo': {
      id: '/monitoreo'
      path: '/monitoreo'
      fullPath: '/monitoreo'
      preLoaderRoute: typeof MonitoreoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formatos': {
      id: '/formatos'
      path: '/formatos'
      fullPath: '/formatos'
      preLoaderRoute: typeof FormatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturacion': {
      id: '/facturacion'
      path: '/facturacion'
      fullPath: '/facturacion'
      preLoaderRoute: typeof FacturacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cumplimiento': {
      id: '/cumplimiento'
      path: '/cumplimiento'
      fullPath: '/cumplimiento'
      preLoaderRoute: typeof CumplimientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuentas': {
      id: '/cuentas'
      path: '/cuentas'
      fullPath: '/cuentas'
      preLoaderRoute: typeof CuentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conductores': {
      id: '/conductores'
      path: '/conductores'
      fullPath: '/conductores'
      preLoaderRoute: typeof ConductoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayuda': {
      id: '/ayuda'
      path: '/ayuda'
      fullPath: '/ayuda'
      preLoaderRoute: typeof AyudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/': {
      id: '/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof CrmIndexRouteImport
      parentRoute: typeof CrmRoute
    }
    '/conductor/': {
      id: '/conductor/'
      path: '/conductor'
      fullPath: '/conductor/'
      preLoaderRoute: typeof ConductorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terminos': {
      id: '/legal/terminos'
      path: '/legal/terminos'
      fullPath: '/legal/terminos'
      preLoaderRoute: typeof LegalTerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacidad': {
      id: '/legal/privacidad'
      path: '/legal/privacidad'
      fullPath: '/legal/privacidad'
      preLoaderRoute: typeof LegalPrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/ventas': {
      id: '/crm/ventas'
      path: '/ventas'
      fullPath: '/crm/ventas'
      preLoaderRoute: typeof CrmVentasRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/pipeline': {
      id: '/crm/pipeline'
      path: '/pipeline'
      fullPath: '/crm/pipeline'
      preLoaderRoute: typeof CrmPipelineRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/login': {
      id: '/crm/login'
      path: '/login'
      fullPath: '/crm/login'
      preLoaderRoute: typeof CrmLoginRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/equipo': {
      id: '/crm/equipo'
      path: '/equipo'
      fullPath: '/crm/equipo'
      preLoaderRoute: typeof CrmEquipoRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/cumpleanos': {
      id: '/crm/cumpleanos'
      path: '/cumpleanos'
      fullPath: '/crm/cumpleanos'
      preLoaderRoute: typeof CrmCumpleanosRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/creditos': {
      id: '/crm/creditos'
      path: '/creditos'
      fullPath: '/crm/creditos'
      preLoaderRoute: typeof CrmCreditosRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/concesionarios': {
      id: '/crm/concesionarios'
      path: '/concesionarios'
      fullPath: '/crm/concesionarios'
      preLoaderRoute: typeof CrmConcesionariosRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/clientes': {
      id: '/crm/clientes'
      path: '/clientes'
      fullPath: '/crm/clientes'
      preLoaderRoute: typeof CrmClientesRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/catalogo': {
      id: '/crm/catalogo'
      path: '/catalogo'
      fullPath: '/crm/catalogo'
      preLoaderRoute: typeof CrmCatalogoRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/capacidades': {
      id: '/crm/capacidades'
      path: '/capacidades'
      fullPath: '/crm/capacidades'
      preLoaderRoute: typeof CrmCapacidadesRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/asesores': {
      id: '/crm/asesores'
      path: '/asesores'
      fullPath: '/crm/asesores'
      preLoaderRoute: typeof CrmAsesoresRouteImport
      parentRoute: typeof CrmRoute
    }
    '/conductor/login': {
      id: '/conductor/login'
      path: '/conductor/login'
      fullPath: '/conductor/login'
      preLoaderRoute: typeof ConductorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conductor/servicio/$id': {
      id: '/conductor/servicio/$id'
      path: '/conductor/servicio/$id'
      fullPath: '/conductor/servicio/$id'
      preLoaderRoute: typeof ConductorServicioIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/conductor-login': {
      id: '/api/public/conductor-login'
      path: '/api/public/conductor-login'
      fullPath: '/api/public/conductor-login'
      preLoaderRoute: typeof ApiPublicConductorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/process': {
      id: '/api/public/push/process'
      path: '/api/public/push/process'
      fullPath: '/api/public/push/process'
      preLoaderRoute: typeof ApiPublicPushProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CrmRouteChildren {
  CrmAsesoresRoute: typeof CrmAsesoresRoute
  CrmCapacidadesRoute: typeof CrmCapacidadesRoute
  CrmCatalogoRoute: typeof CrmCatalogoRoute
  CrmClientesRoute: typeof CrmClientesRoute
  CrmConcesionariosRoute: typeof CrmConcesionariosRoute
  CrmCreditosRoute: typeof CrmCreditosRoute
  CrmCumpleanosRoute: typeof CrmCumpleanosRoute
  CrmEquipoRoute: typeof CrmEquipoRoute
  CrmLoginRoute: typeof CrmLoginRoute
  CrmPipelineRoute: typeof CrmPipelineRoute
  CrmVentasRoute: typeof CrmVentasRoute
  CrmIndexRoute: typeof CrmIndexRoute
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmAsesoresRoute: CrmAsesoresRoute,
  CrmCapacidadesRoute: CrmCapacidadesRoute,
  CrmCatalogoRoute: CrmCatalogoRoute,
  CrmClientesRoute: CrmClientesRoute,
  CrmConcesionariosRoute: CrmConcesionariosRoute,
  CrmCreditosRoute: CrmCreditosRoute,
  CrmCumpleanosRoute: CrmCumpleanosRoute,
  CrmEquipoRoute: CrmEquipoRoute,
  CrmLoginRoute: CrmLoginRoute,
  CrmPipelineRoute: CrmPipelineRoute,
  CrmVentasRoute: CrmVentasRoute,
  CrmIndexRoute: CrmIndexRoute,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  AyudaRoute: AyudaRoute,
  ConductoresRoute: ConductoresRoute,
  CrmRoute: CrmRouteWithChildren,
  CuentasRoute: CuentasRoute,
  CumplimientoRoute: CumplimientoRoute,
  FacturacionRoute: FacturacionRoute,
  FeedbackRoute: FeedbackRoute,
  FormatosRoute: FormatosRoute,
  LoginRoute: LoginRoute,
  MonitoreoRoute: MonitoreoRoute,
  OperacionRoute: OperacionRoute,
  PasajeroRoute: PasajeroRoute,
  PasajerosPcdRoute: PasajerosPcdRoute,
  ReportesRoute: ReportesRoute,
  ServiciosRoute: ServiciosRoute,
  ServiciosFijosRoute: ServiciosFijosRoute,
  TiemposRespuestaRoute: TiemposRespuestaRoute,
  VehiculosRoute: VehiculosRoute,
  ConductorLoginRoute: ConductorLoginRoute,
  LegalPrivacidadRoute: LegalPrivacidadRoute,
  LegalTerminosRoute: LegalTerminosRoute,
  RTokenRoute: RTokenRoute,
  ConductorIndexRoute: ConductorIndexRoute,
  ApiPublicConductorLoginRoute: ApiPublicConductorLoginRoute,
  ConductorServicioIdRoute: ConductorServicioIdRoute,
  ApiPublicPushProcessRoute: ApiPublicPushProcessRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
