/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehiculosRouteImport } from './routes/vehiculos'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as PasajerosPcdRouteImport } from './routes/pasajeros-pcd'
import { Route as PasajeroRouteImport } from './routes/pasajero'
import { Route as OperacionRouteImport } from './routes/operacion'
import { Route as MonitoreoRouteImport } from './routes/monitoreo'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FormatosRouteImport } from './routes/formatos'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as FacturacionRouteImport } from './routes/facturacion'
import { Route as CumplimientoRouteImport } from './routes/cumplimiento'
import { Route as ConductoresRouteImport } from './routes/conductores'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSeedRouteImport } from './routes/api/seed'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const VehiculosRoute = VehiculosRouteImport.update({
  id: '/vehiculos',
  path: '/vehiculos',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const PasajerosPcdRoute = PasajerosPcdRouteImport.update({
  id: '/pasajeros-pcd',
  path: '/pasajeros-pcd',
  getParentRoute: () => rootRouteImport,
} as any)
const PasajeroRoute = PasajeroRouteImport.update({
  id: '/pasajero',
  path: '/pasajero',
  getParentRoute: () => rootRouteImport,
} as any)
const OperacionRoute = OperacionRouteImport.update({
  id: '/operacion',
  path: '/operacion',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoreoRoute = MonitoreoRouteImport.update({
  id: '/monitoreo',
  path: '/monitoreo',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FormatosRoute = FormatosRouteImport.update({
  id: '/formatos',
  path: '/formatos',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturacionRoute = FacturacionRouteImport.update({
  id: '/facturacion',
  path: '/facturacion',
  getParentRoute: () => rootRouteImport,
} as any)
const CumplimientoRoute = CumplimientoRouteImport.update({
  id: '/cumplimiento',
  path: '/cumplimiento',
  getParentRoute: () => rootRouteImport,
} as any)
const ConductoresRoute = ConductoresRouteImport.update({
  id: '/conductores',
  path: '/conductores',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeedRoute = ApiSeedRouteImport.update({
  id: '/api/seed',
  path: '/api/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/conductores': typeof ConductoresRoute
  '/cumplimiento': typeof CumplimientoRoute
  '/facturacion': typeof FacturacionRoute
  '/feedback': typeof FeedbackRoute
  '/formatos': typeof FormatosRoute
  '/login': typeof LoginRoute
  '/monitoreo': typeof MonitoreoRoute
  '/operacion': typeof OperacionRoute
  '/pasajero': typeof PasajeroRoute
  '/pasajeros-pcd': typeof PasajerosPcdRoute
  '/reportes': typeof ReportesRoute
  '/servicios': typeof ServiciosRoute
  '/vehiculos': typeof VehiculosRoute
  '/api/seed': typeof ApiSeedRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/conductores': typeof ConductoresRoute
  '/cumplimiento': typeof CumplimientoRoute
  '/facturacion': typeof FacturacionRoute
  '/feedback': typeof FeedbackRoute
  '/formatos': typeof FormatosRoute
  '/login': typeof LoginRoute
  '/monitoreo': typeof MonitoreoRoute
  '/operacion': typeof OperacionRoute
  '/pasajero': typeof PasajeroRoute
  '/pasajeros-pcd': typeof PasajerosPcdRoute
  '/reportes': typeof ReportesRoute
  '/servicios': typeof ServiciosRoute
  '/vehiculos': typeof VehiculosRoute
  '/api/seed': typeof ApiSeedRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/conductores': typeof ConductoresRoute
  '/cumplimiento': typeof CumplimientoRoute
  '/facturacion': typeof FacturacionRoute
  '/feedback': typeof FeedbackRoute
  '/formatos': typeof FormatosRoute
  '/login': typeof LoginRoute
  '/monitoreo': typeof MonitoreoRoute
  '/operacion': typeof OperacionRoute
  '/pasajero': typeof PasajeroRoute
  '/pasajeros-pcd': typeof PasajerosPcdRoute
  '/reportes': typeof ReportesRoute
  '/servicios': typeof ServiciosRoute
  '/vehiculos': typeof VehiculosRoute
  '/api/seed': typeof ApiSeedRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/conductores'
    | '/cumplimiento'
    | '/facturacion'
    | '/feedback'
    | '/formatos'
    | '/login'
    | '/monitoreo'
    | '/operacion'
    | '/pasajero'
    | '/pasajeros-pcd'
    | '/reportes'
    | '/servicios'
    | '/vehiculos'
    | '/api/seed'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/conductores'
    | '/cumplimiento'
    | '/facturacion'
    | '/feedback'
    | '/formatos'
    | '/login'
    | '/monitoreo'
    | '/operacion'
    | '/pasajero'
    | '/pasajeros-pcd'
    | '/reportes'
    | '/servicios'
    | '/vehiculos'
    | '/api/seed'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/conductores'
    | '/cumplimiento'
    | '/facturacion'
    | '/feedback'
    | '/formatos'
    | '/login'
    | '/monitoreo'
    | '/operacion'
    | '/pasajero'
    | '/pasajeros-pcd'
    | '/reportes'
    | '/servicios'
    | '/vehiculos'
    | '/api/seed'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  ConductoresRoute: typeof ConductoresRoute
  CumplimientoRoute: typeof CumplimientoRoute
  FacturacionRoute: typeof FacturacionRoute
  FeedbackRoute: typeof FeedbackRoute
  FormatosRoute: typeof FormatosRoute
  LoginRoute: typeof LoginRoute
  MonitoreoRoute: typeof MonitoreoRoute
  OperacionRoute: typeof OperacionRoute
  PasajeroRoute: typeof PasajeroRoute
  PasajerosPcdRoute: typeof PasajerosPcdRoute
  ReportesRoute: typeof ReportesRoute
  ServiciosRoute: typeof ServiciosRoute
  VehiculosRoute: typeof VehiculosRoute
  ApiSeedRoute: typeof ApiSeedRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehiculos': {
      id: '/vehiculos'
      path: '/vehiculos'
      fullPath: '/vehiculos'
      preLoaderRoute: typeof VehiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pasajeros-pcd': {
      id: '/pasajeros-pcd'
      path: '/pasajeros-pcd'
      fullPath: '/pasajeros-pcd'
      preLoaderRoute: typeof PasajerosPcdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pasajero': {
      id: '/pasajero'
      path: '/pasajero'
      fullPath: '/pasajero'
      preLoaderRoute: typeof PasajeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operacion': {
      id: '/operacion'
      path: '/operacion'
      fullPath: '/operacion'
      preLoaderRoute: typeof OperacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoreo': {
      id: '/monitoreo'
      path: '/monitoreo'
      fullPath: '/monitoreo'
      preLoaderRoute: typeof MonitoreoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formatos': {
      id: '/formatos'
      path: '/formatos'
      fullPath: '/formatos'
      preLoaderRoute: typeof FormatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturacion': {
      id: '/facturacion'
      path: '/facturacion'
      fullPath: '/facturacion'
      preLoaderRoute: typeof FacturacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cumplimiento': {
      id: '/cumplimiento'
      path: '/cumplimiento'
      fullPath: '/cumplimiento'
      preLoaderRoute: typeof CumplimientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conductores': {
      id: '/conductores'
      path: '/conductores'
      fullPath: '/conductores'
      preLoaderRoute: typeof ConductoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seed': {
      id: '/api/seed'
      path: '/api/seed'
      fullPath: '/api/seed'
      preLoaderRoute: typeof ApiSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  ConductoresRoute: ConductoresRoute,
  CumplimientoRoute: CumplimientoRoute,
  FacturacionRoute: FacturacionRoute,
  FeedbackRoute: FeedbackRoute,
  FormatosRoute: FormatosRoute,
  LoginRoute: LoginRoute,
  MonitoreoRoute: MonitoreoRoute,
  OperacionRoute: OperacionRoute,
  PasajeroRoute: PasajeroRoute,
  PasajerosPcdRoute: PasajerosPcdRoute,
  ReportesRoute: ReportesRoute,
  ServiciosRoute: ServiciosRoute,
  VehiculosRoute: VehiculosRoute,
  ApiSeedRoute: ApiSeedRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
